/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#18a0fb",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#001d34",
        "secondary": "#565e74",
        "tertiary-fixed": "#dfe3e7",
        "background": "#f8f9ff",
        "on-tertiary-fixed-variant": "#43474b",
        "secondary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#9acbff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "tertiary": "#5a5f62",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#00629e",
        "on-surface": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3f4852",
        "outline": "#6f7883",
        "outline-variant": "#bfc7d4",
        "border-subtle": "#E2E8F0",
        "primary-fixed": "#cfe5ff",
        "surface-white": "#FFFFFF",
        "primary": "#00629e",
        "on-tertiary-fixed": "#171c1f",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#2e3336",
        "warning-amber": "#F59E0B",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-primary-fixed-variant": "#004a79",
        "surface-dim": "#cbdbf5",
        "surface-container-low": "#eff4ff",
        "success-green": "#22C55E",
        "inverse-surface": "#213145",
        "tertiary-fixed-dim": "#c3c7cb",
        "tertiary-container": "#969b9f",
        "on-primary-container": "#003458",
        "surface-variant": "#d3e4fe",
        "inverse-primary": "#9acbff",
        "surface": "#f8f9ff",
        "error": "#ba1a1a",
        "surface-container-high": "#dce9ff"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "base": "4px"
      }
    },
  },
  plugins: [],
}